// Generates THIRD_PARTY_NOTICES.md from the packages that actually end up in the bundles
// (esbuild metafile), with each package's license text.
// Usage: node scripts/notices.mjs [--check]   (--check fails if the committed file is outdated)
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import * as esbuild from 'esbuild';
import { bundles } from './bundles.mjs';

const check = process.argv.includes('--check');
const packages = new Map();

for (const options of bundles({ production: true })) {
  const { metafile } = await esbuild.build({
    ...options,
    write: false,
    metafile: true,
    logLevel: 'silent',
  });
  for (const input of Object.keys(metafile.inputs)) {
    const match = /node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(input.replaceAll('\\', '/'));
    if (!match) continue;
    const dir = input.slice(0, input.replaceAll('\\', '/').indexOf(match[0]) + match[0].length);
    packages.set(match[1], dir);
  }
}

const licenseFile = (dir) => {
  const name = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.(md|txt))?$/i.test(f));
  return name ? readFileSync(join(dir, name), 'utf8').trim() : undefined;
};

const sections = [...packages.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, dir]) => {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    const text =
      licenseFile(dir) ?? `License: ${pkg.license ?? 'unknown'} (no license file in package)`;
    return `## ${name} ${pkg.version}\n\nLicense: ${pkg.license ?? 'see below'}\n\n\`\`\`text\n${text}\n\`\`\`\n`;
  });

const content = `# Third-Party Notices

Bizmo bundles the following third-party packages. This file is generated by \`npm run notices\`
from the packages included in the production bundles.

bpmn-js, dmn-js, and form-js are distributed under the bpmn.io license, which requires that the
bpmn.io project watermark remains visible in the editors. Bizmo does not remove or hide it.

${sections.join('\n')}`;

const target = 'THIRD_PARTY_NOTICES.md';
if (check) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== content) {
    console.error(`${target} is outdated. Run \`npm run notices\`.`);
    process.exit(1);
  }
  console.log(`${target} is up to date (${packages.size} packages).`);
} else {
  writeFileSync(target, content);
  console.log(`Wrote ${target} (${packages.size} packages).`);
}
