// Generates THIRD_PARTY_NOTICES.md from the packages that actually end up in the bundles
// (esbuild metafile), with each package's license text.
// Usage: node scripts/notices.mjs [--check]   (--check fails if the committed file is outdated)
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import * as esbuild from 'esbuild';
import { bundles } from './bundles.mjs';

const check = process.argv.includes('--check');
const packages = new Map();

for (const options of bundles({ production: true })) {
  const { metafile } = await esbuild.build({
    ...options,
    write: false,
    metafile: true,
    logLevel: 'silent',
  });
  for (const input of Object.keys(metafile.inputs)) {
    const match = /node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(input.replaceAll('\\', '/'));
    if (!match) continue;
    const dir = input.slice(0, input.replaceAll('\\', '/').indexOf(match[0]) + match[0].length);
    packages.set(match[1], dir);
  }
}

const readFirst = (dir, pattern) => {
  const name = readdirSync(dir).find((f) => pattern.test(f));
  return name ? readFileSync(join(dir, name), 'utf8').trim() : undefined;
};

const MIT_TEXT = `Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`;

const authorOf = (pkg) =>
  typeof pkg.author === 'string' ? pkg.author : (pkg.author?.name ?? `the ${pkg.name} authors`);

/** License text: the package's license file, or the standard MIT text for MIT packages without one. */
function licenseText(dir, pkg) {
  const file = readFirst(dir, /^(licen[cs]e|copying)(\.(md|txt))?$/i);
  if (file) return file;
  if (pkg.license === 'MIT') {
    return `MIT License (no license file in the package; standard text with the author from package.json)\n\nCopyright (c) ${authorOf(pkg)}\n\n${MIT_TEXT}`;
  }
  console.error(`No license text for ${pkg.name} (${pkg.license ?? 'no license field'})`);
  process.exitCode = 1;
  return `License: ${pkg.license ?? 'unknown'}`;
}

const sections = [...packages.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, dir]) => {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
    // Apache-2.0 and some others require reproducing a NOTICE file when present.
    const notice = readFirst(dir, /^notice(\.(md|txt))?$/i);
    const blocks = [licenseText(dir, pkg), ...(notice ? [`NOTICE:\n\n${notice}`] : [])];
    return `## ${name} ${pkg.version}\n\nLicense: ${pkg.license ?? 'see below'}\n\n${blocks.map((b) => `\`\`\`text\n${b}\n\`\`\`\n`).join('\n')}`;
  });

const content = `# Third-Party Notices

Bizmo bundles the following third-party packages. This file is generated by \`npm run notices\`
from the packages included in the production bundles.

bpmn-js, dmn-js, and form-js are distributed under the bpmn.io license, which requires that the
bpmn.io project watermark remains visible in the editors. Bizmo does not remove or hide it.

${sections.join('\n')}`;

const target = 'THIRD_PARTY_NOTICES.md';
if (check) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== content) {
    console.error(`${target} is outdated. Run \`npm run notices\`.`);
    process.exit(1);
  }
  console.log(`${target} is up to date (${packages.size} packages).`);
} else {
  writeFileSync(target, content);
  console.log(`Wrote ${target} (${packages.size} packages).`);
}
